name: github pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build (PR)
        if: ${{ github.event_name == 'pull_request' }}
        run: hugo --baseURL https://pinkehaende.github.io/website/pr${{ github.event.pull_request.number }}

      - name: Deploy (PR)
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ./pr${{ github.event.pull_request.number }}

      - name: Build (master)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: hugo --minify --baseURL https://pinkehaende.github.io/website/

      - name: Deploy (master)
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
